name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          options: "--check --verbose --target-version py39"
      - uses: psf/black@stable
